### ISSUE TITLE
Initial suggestions for plugin release

### ISSUE THREAD

**Issue by misraved** [francois2metz/steampipe-plugin-baleen#1]
Hey @francois2metz , great work on the new plugin 👍 

The basic structure and results look good so far. While using the plugin, we did come up with a few suggestions based on our best practices:

- The examples in `baleen_namespace`, `baleen_owasp`,  `baleen_redirect_rule`, `baleen_rewrite_rule` tables doc seem light. Could you please add 2-3 more examples expanding their usage?
- Also in `config/baleen.spc` file,is the API format a UUID like “xxxxx-xxx-xxxx-xxxx-xxxx”?
- The plugin doesn’t seem to implement `Backoff and retry`, `Maximum concurrency` and  `Context cancellation` logic across the tables. Is there no support for it? Please refer to this [link](https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion) for more information.
- Does the SDK/API support pagination at all?

**Comment by francois2metz** [comment]
> Hey @francois2metz , great work on the new plugin +1
> 
> The basic structure and results look good so far. While using the plugin, we did come up with a few suggestions based on our best practices:
> 
>     * The examples in `baleen_namespace`, `baleen_owasp`,  `baleen_redirect_rule`, `baleen_rewrite_rule` tables doc seem light. Could you please add 2-3 more examples expanding their usage?

I added some examples for the namespace table that was empty. I have no ideas for the others tables :(

>     * Also in `config/baleen.spc` file,is the API format a UUID like “xxxxx-xxx-xxxx-xxxx-xxxx”?
Yes

>     * The plugin doesn’t seem to implement `Backoff and retry`, `Maximum concurrency` and  `Context cancellation` logic across the tables. Is there no support for it? Please refer to this [link](https://steampipe.io/docs/develop/plugin-release-checklist#data-ingestion) for more information.

There is no rate limit and never encounter errors. That's why I thought I will be ok. I can take a look if you want.

>     * Does the SDK/API support pagination at all?
There is no pagination right now.

**Comment by misraved** [comment]
Thanks @francois2metz for the feedback 👍. The overall changes look good.

For the social graphic image would you like to use the following query - 

```
select
  id,
  name
from
  baleen_namespace;
``` 

Once again, great work on the plugin 👍 . Excited to see this one up on hub 😃

**Comment by francois2metz** [comment]
> Thanks @francois2metz for the feedback +1. The overall changes look good.
> 
> For the social graphic image would you like to use the following query -
> 
> ```
> select
>   id,
>   name
> from
>   baleen_namespace;
> ```

I updated the query to include the `url` which is a nice addition for my use case ;)

> Additionally, I am unable to render the `baleen.svg` file [here](https://github.com/francois2metz/steampipe-plugin-baleen/blob/main/docs/baleen.svg). Am I missing something?

Same for me. I generated a new one.

> 
> Once again, great work on the plugin +1 . Excited to see this one up on hub smiley

Thanks!

:warning: For some reasons the plugin is no longer working with the namespace table. It seems that the API has changed. I need to take a look at it:
> Error: error unmarshalling JSON: "parsing time \"1654255125.378450000\" as \"\\\"2006-01-02T15:04:05Z07:00\\\"\": cannot parse \"1654255125.378450000\" as \"\\\"\"" (SQLSTATE HV000)

**Comment by misraved** [comment]
Thanks @francois2metz for the super quick response 👍. I can now see the image as well 👍 

I will wait for a while then, please let me know in case you have more questions 👍

**Comment by francois2metz** [comment]
> I will wait for a while then, please let me know in case you have more questions +1

I fixed the issue. This should be ready to release.

**Comment by misraved** [comment]
Thanks @francois2metz for fixing the issue 👍
